### ISSUE TITLE
Data download error - not letting me download

### ISSUE THREAD

**Issue by j-booth4** [qiceradar/qiceradar_plugin#11]
When I try downloading data from CRESIS, it produces this error message: 
<img width="1470" alt="Screenshot 2024-06-27 at 11 40 29 AM" src="https://github.com/qiceradar/qiceradar_plugin/assets/173849537/5ea9bc7f-9035-4a0e-bd27-4ac6f3b5f05e">

A similar message occurs when I try downloading from UTIG, but I'm able to successfully download from BAS. I haven't tried any other institutions yet besides these three. I tried closing and reopening the project, and reloading the plugin, but the error didn't change.

**Comment by lauralindzey** [comment]
Hi @j-booth4 -- I'm sorry, I should have been clearer! The version you're running doesn't **yet** support CRESIS & UTIG data; I'll be rolling that out very soon, and will let you know when you should try again.
