### ISSUE TITLE
Error when trying to view data

### ISSUE THREAD

**Issue by j-booth4** [qiceradar/qiceradar_plugin#12]
I freshly downloaded some BAS data (and confirmed it downloaded to my device). When I try to view the flight path radar, this error pops up: 
<img width="1470" alt="Screenshot 2024-06-27 at 11 44 12 AM" src="https://github.com/qiceradar/qiceradar_plugin/assets/173849537/a2e3a83b-387a-4442-8070-8221f2ba787c">
I also tried to close and reopen the program but the error still occurs.

**Comment by lauralindzey** [comment]
Huh. This is obviously a bug somewhere that I need to fix, but I can't figure it out from this alone. 
1) Can you try:
  - restart QGIS
  -  use the Plugin Reloader to reload QIceRadar
  - then try viewing data again?
 (If this fixes it, it means there's some logic in my handling of the reload signal that doesn't get execute on the initial load)

2) While you're testing that, can you also scroll up on your layers panel and see if you have a "Radar Viewer" group?
