### ISSUE TITLE
GB-large download bar error

### ISSUE THREAD

**Issue by j-booth4** [qiceradar/qiceradar_plugin#22]
After pulling and reloading the plug-in, I'm now able to download the 3-GB data, yay! However, the download bar doesn't function as I was expecting. It does for the first 60% or so, but then the completed / total fractions switches to a negative value. 
<img width="1470" alt="Starts Positive" src="https://github.com/qiceradar/qiceradar_plugin/assets/173849537/28a44661-0fef-49f8-bcfb-4f14a33dacdb">
A couple notes about this screenshot:
- P25A was the first 3-GB file I downloaded. P34A is mid-download.
- Once P25A started downloading, the 'bytes downloaded' was positive and increasing, along with % increasing from 0, but then midway it switched to a negative number that increased towards 0. 
- The P25A download bar froze at the value shown, but the status on the left changed to Finished (and it did finish downloading to my folder)
- P34A experienced the exact same thing.
- I downloaded a different 500-MB file that functioned as normal (reached 100%)

**Comment by lauralindzey** [comment]
Oh, yuck. Turns out that while in python3 `int`s don't overflow, in Qt's bindings, an int becomes an int32 and most definitely does overflow.

This SO post is my exact problem: https://stackoverflow.com/questions/77478821/how-to-emit-a-64-bit-unsigned-integer-with-a-pyqt-signal

Should be an easy fix.

**Comment by lauralindzey** [comment]
I tested my fix on P25, and the progress bar now works:
<img width="1542" alt="image" src="https://github.com/qiceradar/qiceradar_plugin/assets/65185744/f2461157-d223-41e9-9b66-0f632dc8c39d">
