### ISSUE TITLE
Color Limits slider has no increments

### ISSUE THREAD

**Issue by j-booth4** [qiceradar/qiceradar_plugin#35]
When I'm trying to change the color limits, e.g. increase the minimum by 0.1, I keep having to type an increase by 0.1 because the slider doesn't have increments of this size. When I use the slider to increase the color, it automatically jumps by 0.5 (which is a lot given the difference between the default min and max values). 
Default color limits:
<img width="1157" alt="Color Slider - Default" src="https://github.com/user-attachments/assets/ec8c7bf3-65da-4fcd-82e0-bf4b10f37552">
Increasing the minimum by one increment of the slider: 
<img width="1157" alt="Color Slider - Increment up" src="https://github.com/user-attachments/assets/5e768727-8952-4115-8ac7-ca637447a74d">
Then when I tried to decrement back to the original, it decreased by 1.0
<img width="1157" alt="Color slider - increment down" src="https://github.com/user-attachments/assets/47307b8a-1f0e-441d-8814-29bb4770bed0">
It would be useful if the slider has set increments of 0.1, or something that adjusts to a radargram's default min/max

**Comment by j-booth4** [comment]
Also, when I type 0.05 increments, e.g. changing 4.6 to 4.65, it will change the color as expected and display the rounded number of 4.7. But weirdly, if I interact with the side panel (e.g. turn off crosshair) it shifts the color to true 4.7. 

It's hard to take screenshots of, so I can show you in person. Just a slightly weird bug

**Comment by lauralindzey** [comment]
Thanks for the report @j-booth4! I just reproduced both of these issues. 

The viewer was originally developed for radargrams with intensity values ~100,000, so originally supported integer color limits. However, many of the data sources we're using now have a much smaller range!

I'll be taking a look at the color sliders anyways thanks to changes in newer versions of matplotlib that turned a warning into an error, and will try to fix both oddnesses while I'm at it.

**Comment by lauralindzey** [comment]
I made a lot of changes to the sliders in 77f25d8, including addressing these issues.

@j-booth4 -- can you pull the most recent code and confirm that the redone sliders make sense + work for you?

**Comment by lauralindzey** [comment]
Augh. It turns out that RangeSlider was introduced in matplotlib 3.4, which dates to 2021. And, despite having an only months-old laptop, @j-booth4's QGIS install is using matplotlib 3.3. (system version is 3.8)

**Comment by lauralindzey** [comment]
This has been resolved by using a pair of sliders in the case where RangeSlider isn't available.
