### ISSUE TITLE
CRESIS data availability

### ISSUE THREAD

**Issue by j-booth4** [qiceradar/qiceradar_plugin#39]
Pretty please make the CRESIS data available for us to download!

**Comment by lauralindzey** [comment]
On the TODO list, and I know it's critical for your project! ETA Monday ...

**Comment by lauralindzey** [comment]
All CRESIS Antarctic data is now supported by the viewer! 

@j-booth4 -- if you want to look at the other surveys the flew around the pole, you just need to pull the code; the same database you were using earlier today will be fine. 

I still need to iterate with John Paden about preferred metadata, but that's a separate issue, and not one tracked in this repo.
